config/routes.rb
Spree::Core::Engine.routes.draw do
  resources :stock_emails, only: :create

  namespace :admin do
    resources :products do
      resources :stock_emails
    end
  end
end

app/models/spree/stock_email.rb
class Spree::StockEmail < ActiveRecord::Base

  belongs_to :product

  validates :product, presence: true
  validates :email, presence: true, email: true
  validates_uniqueness_of :email, conditions: -> { where(sent_at: nil) }, scope: :product_id, message: Spree.t('stock_email.messages.already_registered')

  def self.not_sent(product)
    where(sent_at: nil, product_id: product.id)
  end

  def self.notify(product)
    self.not_sent(product).each { |e| e.notify }
  end

  def notify
    Spree::StockEmailsMailer.stock_email(self).deliver
    mark_as_sent
  end

  private

  def mark_as_sent
    update_attribute :sent_at, Time.zone.now
  end
end

app/models/stock_notifier.rb
require 'sendwithus_ruby_action_mailer'
class StockNotifier < ::SendWithUsMailer::Base

  default from: 'atendimento@dragonflyvc.com'

  def order_stocked(recipient, orders)

      assign :product, {name: orders}

      mail(
          email_id: 'tem_sXehtjXLfBEHBUCDv27MXd',
          recipient_address: recipient,
      )
  end
end

app/controllers/spree/admin/stock_emails_controller.rb
module Spree
  module Admin
    class StockEmailsController < ResourceController
      before_filter :load_data

      def collection_url(options = {})
        admin_product_stock_emails_url
      end

      def load_data
        @product = Product.find_by(:slug => params[:product_id])
        @stock_emails = Spree::StockEmail.where(product_id: @product.id)
      end
    end
  end
end

app/controllers/spree/admin/stock_items_controller_decorator.rb
Spree::Admin::StockItemsController.class_eval do

  before_filter :set_current_on_hand_value, only: :create
  after_filter :send_stock_emails, only: :create

  def set_current_on_hand_value
    @variant = Spree::Variant.find(params[:variant_id])
    @product_was_in_stock = product_in_stock?(@variant.product)
  end

  def send_stock_emails
    Spree::StockEmail.notify(@variant.product) if !@product_was_in_stock && @variant.in_stock?
  end

  private

  def product_in_stock?(product)
    product.total_on_hand > 0
  end
end

app/controllers/spree/stock_emails_controller.rb
class Spree::StockEmailsController < ApplicationController

  def create
    product = Spree::Product.find_by(:id => stock_email_params[:product])
    redirect_to :back and return unless product

    current_email = spree_current_user ? spree_current_user.email : stock_email_params[:email]
    stock_email = Spree::StockEmail.new(product: product, email: current_email)
    if stock_email.save
      flash[:success] = Spree.t('stock_email.messages.back_in_stock_email_message', product: product.name)
    else
      flash[:notice] = stock_email.errors.full_messages.join(', ')
    end

    redirect_to :back
  end

  private

    def stock_email_params
      params.require(:stock_email).permit([:product, :email])
    end
end

app/views/spree/admin/products/_stock_mailer_menu.html.erb
<%= content_tag :li, :class => ('active' if current == 'Stock Mailer') do %>
<%= link_to_with_icon 'icon-envelope', Spree.t(:stock_mailer), admin_product_stock_emails_url(@product) %>
<% end if can?(:admin, Spree::StockEmail) %>

app/views/spree/admin/stock_emails/_form.html.erb
<div data-hook="admin_stock_mailer_form_fields">
  <div class="four columns alpha">
    <div data-hook="email" class="field">
      <%= f.label Spree.t(:email) %><br>
      <%= f.email_field :email %>
    </div>
  </div>
  <div class="four columns alpha">
    <div data-hook="sent_at" class="field">
      <%= f.label Spree.t(:sent_at) %><br>
      <%= f.text_field :sent_at, :value => datepicker_field_value(@stock_email.sent_at), :class => 'datepicker datepicker-from' %>
    </div>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/stock_emails/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Stock Mailer' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @stock_email } %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_stock_mailer), admin_product_stock_emails_url(@product), :icon => 'icon-arrow-left' %></li>
<% end %>

<%= form_for [:admin, @product, @stock_email] do |f| %>
  <fieldset data-hook="edit_image">
    <div class="eleven columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>
    </div>
    <div class="clear"></div>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'icon-refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to Spree.t('actions.cancel'), admin_product_stock_emails_url(@product), :id => 'cancel_link', :class => 'button icon-remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/stock_emails/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Stock Mailer'} %>

<table class="index">
  <thead data-hook="stock_mailer_header">
    <tr>
      <th><%= Spree.t(:email) %></th>
      <th><%= Spree.t(:sent_at) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @stock_emails.each do |se| %>
      <tr id="stock_email_<%= se.id %>">
        <td class="align-center"><%= se.email %></td>
        <td class="align-center">
          <% sent_at_text = se.sent_at ? I18n.l(se.sent_at, format: '%a, %d %b %Y %H:%M:%S') : Spree.t(:not_sent) %>
          <%= sent_at_text %>
        </td>
        <td class="actions">
          <%= link_to_edit_url edit_admin_product_stock_email_url(@product, se), no_text: true %>
          <%= link_to_delete '', { url: admin_product_stock_email_url(@product, se), no_text: true } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>